# Generated by Django 4.2.5 on 2024-05-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TorogozApp', '0005_alter_tablacreditos_id_tabla_general_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablarutas',
            name='nombre_trabajador',
        ),
    ]
